### ISSUE TITLE
Articles aren't properly sorted by date

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#142]
Now it happened to me, that some old articles are sorted in between current articles (but the articles of this particular stream are correctly sorted by date and next to each other instead of mixed with the others).

Fedora 24 / FR 1.6b / Console: http://pastebin.com/5qMMsxMt

![auswahl_002](https://cloud.githubusercontent.com/assets/10520767/16157045/3f5acd60-34b7-11e6-9049-778f9b2099f2.png)

**Comment by jangernert** [comment]
The default behavior of FeedReader is to display the articles in the order it received it from the back-end. If you want to sort them by date just go to the settings and choose "date".
Does this still happen after changing the setting?

**Comment by fb87** [comment]
It was sorted by date everytime (before and after), except in this case. Thought I encountered a quirk and reported it.

**Comment by jangernert** [comment]
Yes, because most of the time the back-end gets the articles in the correct time-order. But at least with tt-rss it happened sometimes that older articles got added to tt-rss later. So I changed the default to "received" so the unread articles always will appear at the top of the list.
So is this resolved?

**Comment by fb87** [comment]
I think so.
