### ISSUE TITLE
Database empty after sync

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#143]
After getting a notification about new articles, the article list was cleared and so was the article view with the article I currently read. Took about 10 seconds and some clicking around for getting everything displayed again.

Fedora 24
FR 1.6b

**Comment by jangernert** [comment]
Again, you seem to be experiencing a bug where the updateArticleList function triggers way to often. This is probably ONE of the many symptoms this behavior causes. So you DONT need to report EACH AND EVERY ONE of these ... only if this still happens after fixing the original bug

**Comment by fb87** [comment]
And all my articles were deleted again. This time without having done a single thing.

[feedreader.tar.gz](https://github.com/jangernert/FeedReader/files/376853/feedreader.tar.gz)

**Comment by jangernert** [comment]
Okay, the watchdog did detect the deleting-actions. Now the only question is: what is triggering this.
Before writing the feeds to the db I reset the "subscribed" bit and set it again for each feed when it gets written to the db. After this I delete all the feeds and their articles that still don't have their "subscribed"-flag set.
Maybe this is going wrong for you?
I added some more prints to better see what's happening during this step. Can you try to trigger the bug again?

**Comment by fb87** [comment]
k

**Comment by fb87** [comment]
Now it happened again and the whole DB was cleared.

[feedreader.tar.gz](https://github.com/jangernert/FeedReader/files/418212/feedreader.tar.gz)

**Comment by jangernert** [comment]
Jup, it seems like the flag that the categories and feeds still exist does not get set. And therefore FeedReader deletes the categories, the feeds in that category and all the articles of the feeds after the sync.
No idea why the flag does not get set for you in some rare cases.

**Comment by jangernert** [comment]
Okay, so now it happened to me as well. After 2 years without even touching my home-server (which runs a tt-rss instance) didn't respond to calls over the local network anymore (just restarted it).
But here is the interesting part:
Somehow the online-check before the actual snyc went fine. But the server didn't return any useful data. Which means in turn that FeedReader deleted all categories and feeds because it thought they must have been deleted by the user on the server.

Seems like you or feedly are having networking problems quite often :D

I just committed some code that checks for all kinds of errors during the retrieval of categories and feeds 61ee0193ed9fcbe8a359c3217e1f9ed62dfe88bb.

**Comment by fb87** [comment]
Well, congrats! ;P   I'll try it.

**Comment by jangernert** [comment]
So, I'm going to close this for now.
I haven't tested the patches very much, since it's very hard to recreate the exact situation. But I'm pretty sure this bug should not recur.
If it's not fixed after all, just reopen it.
