### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by fturco** [jangernert/FeedReader#156]
Feed Reader crashed (segmentation fault) after a small amount of time after having requested feed updating. In the meantime I was also reading feeds that were already there (unread mode). It happened several times before, but now I launched it via gdb after having rebuild several packages for getting rid of ?? in backtraces.

Package versions:
- glib2 2.48.1-1
- webkit2gtk 2.12.3-1.nonprism1
- dconf 0.26.0-1
- gtk3 3.20.6-1
- feedreader-git 1.6.beta.1.r105.g83daf37-1

Distribution: Parabola GNU/Linux-libre

[backtrace.log.txt](https://github.com/jangernert/FeedReader/files/378712/backtrace.log.txt)
[daemon.log.txt](https://github.com/jangernert/FeedReader/files/378710/daemon.log.txt)
[ui.log.txt](https://github.com/jangernert/FeedReader/files/378711/ui.log.txt)

It took a lot of time for this test, especially due to webkit2gtk build process. That package alone (with unstripped binaries and debug symbols) is 4,58 GiB in size!

**Comment by jangernert** [comment]
You rebuilt webkit2? oO I don't think that was necessary :D
Before reading any logs: Did the UI (feedreader) or the daemon (feedreader-daemon) segfault?

**Comment by fturco** [comment]
I'm not sure, but I can tell you that after launching `gdb` I issued the `exec feedreader` command, not `exec feedreader-daemon`.

**Comment by jangernert** [comment]
If the daemon crashes, you usually don't even notice at first. If the UI crashes it is quite obvious. ;)

How did you generate the backtrace? I just took a quick look and was overwhelmed by information :D Lots of different threads of glib, webkit and so on.
Every time I had to debug a segfault I followed this quick explanation here: http://www.unknownroad.com/rtfm/gdbtut/gdbsegfault.html
And usually found at least the function that was causing the crash quickly. At least the log was very readable and understandable if you know the code-base.

**Comment by fturco** [comment]
I used the `thread apply all bt full` command as described [here](https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces).

**Comment by jangernert** [comment]
Can you also generate a simple backtrace for me?

**Comment by fturco** [comment]
Sure. Tomorrow I'll try to reproduce the problem again and generate a less verbose backtrace.

**Comment by fturco** [comment]
Here you are the simple backtrace. This time I simply used the `bt` command.

[backtrace-simple.log.txt](https://github.com/jangernert/FeedReader/files/379431/backtrace-simple.log.txt)

**Comment by jangernert** [comment]
Much easier to find the relevant information. After reading the simple backtrace the full one also started to make sense :P
But I am still not sure what is causing the segfault, since all that is listed are glib and gtk functions. But afaik the only time that a glib timeout leads to a "gtk_list_box_remove" is the removeRow() function in ArticleList.vala.
So how did you trigger the segfault? Maybe by reading articles in the "unread"-mode? Or triggering a update of the article-list (during a sync)?
If that is the case you can try to remove line 995-998 in src/Widgets/ArticleList.vala (basically the timeout that removes the row). Is that what is causing your segfault?

**Comment by fturco** [comment]
Yes, I was reading articles in unread mode after having triggered an update.
I'll try editing that file later as you described.

**Comment by fturco** [comment]
I patched `ArticleList.vala` as you said and rebuilt Feed Reader. Then I tested it for about 40 minutes. It hasn't crashed so far.

**Comment by jangernert** [comment]
That leads to the question: why is this problematic for you, but not for everybody else?
Can you try to increase the time of the timeout a little bit? So that the remove happens a few milliseconds after the reveal (hiding the row)? Maybe there are some timing problems.
So for example 

`GLib.Timeout.add(time+50, () => {`

**Comment by fturco** [comment]
Which `GLib.Timeout.add` line should I edit? That inside the `limitScroll` function? In addition to that, should I still remove lines 995-998 or should I keep them? Can you give me a patch file, just to be sure?

**Comment by jangernert** [comment]
Sorry, if it wasn't clear. I meant re-add the lines removed and add a little bit to the time variable of the timeout.
I committed the change 634695e

**Comment by fturco** [comment]
I built r113 without applying any custom patch as it seems you already patched it. Then I tested it briefly (10 minutes), and it didn't crash. I feel I need more time to test this version more thoroughly , but I have no more unread feeds at the moment.

**Comment by fturco** [comment]
After almost one hour of testing I haven't experienced any problem or crash.
