### ISSUE TITLE
Make expand/collapse-button easier to hit

### ISSUE THREAD

**Issue by horosgrisa** [jangernert/FeedReader#184]
Now you can fold/unfold category when click at icon. For me is very hard to click icon because I use tablet with touchscreen. You can add posibility to fold categories when you click at name of category. Similar behaviour is in Geary.

**Comment by jangernert** [comment]
Well, in geary it doesn't make much sense to select a category. All you can do is collapse/expand them. In FeedReader you want the category itself to be selectable.
Also I don't want FeedReader try to do everything and work everywhere at once. I want to keep the application focused. If you open the website, the first headline is "RSS desktop client". I don't really want to go the ubuntu-road and design everything to kinda work on tablets and phones, but do lots of compromises.
FeedReader utilizes mouse-hovers, left-clicks and scroll-wheel-clicks.
So I hope you understand my point of view. If we can improve things on touch-screens without compromising anything on the desktop, sure why not. But I don't want to have "meh" solutions on the desktop because they work better on tablets.

**Comment by horosgrisa** [comment]
I understand your point of view and I dont demand big changes in FeedReader. I do not think that this change will be damage PC users. Contrary it will be even more comfortable.

**Comment by jangernert** [comment]
Then how would you select categories, if clicking on the row will just collapse/expand it?

**Comment by jangernert** [comment]
I just doubled the width of the event-box from 16 to 32 pixels. This should make it much easier to hit.
Hope this will be enough for you on touchpad.
I will commit the changes soon. (first have to tie up some loose ends :D)

**Comment by jangernert** [comment]
Changes are in master now.
