### ISSUE TITLE
include option to render entire web page

### ISSUE THREAD

**Issue by mateomiguel** [jangernert/FeedReader#188]
I am a wierdo in that I like to subscribe to RSS feeds but then want to see the entire web page that they point to in the reader window. Can that be an option?

**Comment by jangernert** [comment]
No!
There has to be a point where I stop adding random settings because 5 people out there use it. I want to keep the application focused and imo added way to many settings already.
If you want to open the website, double click the article-row, click the title or press "o" to open the link in the default browser.
If that is not what you want, there are always alternatives out there that can be customized in any way imaginable
* [Akregator](https://userbase.kde.org/Akregator/en)
* [liferea](https://lzone.de/liferea/)
* [RSSOwl](http://www.rssowl.org/)

I'm sure one of these has all the features you want.
