### ISSUE TITLE
Articles are displayed in wrong order

### ISSUE THREAD

**Issue by quassy** [jangernert/FeedReader#214]
Articles for many feeds are not displayed in chronological order (all articles are marked as read and are not starred) for example:

[Design Tagebuch](http://www.designtagebuch.de/feed/)
```
07.09.
06.09.
...
26.08.
23.09.
```

[Carta](http://www.carta.info/feed/)
```
08.09.
05.09.
...
27.08.
Yesterday
23.09.
23.09.
```

Using elementary OS 0.4 Loki with FeedReader 1.6.2 (from stable PPA) and Feedly backend.

**Comment by jangernert** [comment]
What did you set to sort them by? Date or received?

**Comment by quassy** [comment]
Oh, I still had it at the default "received". Switching to "date" fixed it.

**Comment by jangernert** [comment]
Okay, then I'll close this.
The reason I have 'received' as default is because at least ttrss sometimes fetches newer articles first and then some old ones later on. So it could happen that older unread articles would get sorted into the list way down. And at least I want an article to be on top of the list if I haven't seen it before.
