### ISSUE TITLE
News counters for starred category

### ISSUE THREAD

**Issue by fb87** [jangernert/FeedReader#231]
Would be nice if the news counters could display the amount of starred news of the according feed, if starred category is selected. At the moment they still act as unread counters, even when starred category is selected.

**Comment by fb87** [comment]
Hi Jan, thanks! I just pulled the new code, but somehow I can't tell any difference and I don't see any counts for marked articles?

**Comment by jangernert** [comment]
Have you checked if you run the latest commit with "feedreader --version" ?

**Comment by fb87** [comment]
$ feedreader --version
Version: 2.0-dev
Git Commit: b04b2da7b0cfae02eafcabd661e8b32d22945a6a

**Comment by jangernert** [comment]
That build does not include the latest 3 commits from master.

**Comment by fb87** [comment]
Do you know how I can sync git to the current status? Obviously it's behind, whysoever…

**Comment by jangernert** [comment]
For starters I would check if the issue is caused by git or by the build. Does 'git log' show the last 3 commits?
- show marked-article-count in feedlist if article-list is in marked-state to fix #231
- also take ArticleListState into consideration when creating a new feedlist
- deactive mark-as-read by hovering over unread-count if showing makred-count

If that is the case you should try to delete your build-folder and do a clean build once again.

**Comment by fb87** [comment]
This was the case, the last time I did `cmake ..` is already some time ago. I never know when to do it and when I don't need to do. I deleted everything and built it again, now it works, thanks!
