### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by fbruetting** [jangernert/FeedReader#251]
[master]
On my i7, FR produces a constant amount of load of about 10% (of one core) without doing anything other than displaying an article (even killed the daemon and minimized the window, result is the same).

**Comment by jangernert** [comment]
Switching between window states (e.g. foreground/background) causes 2-5% CPU-load on my machine, but that is just because gtk+ has to rerender everything for the new state. Corebird for example shows similar load. When totally idling load goes down to 0%.
Can you investigate what the binary is doing? A gdb-backtrace, from a point where the everything is loaded for a few seconds and the CPU-usage is still high, would be enough for the beginning.

**Comment by fbruetting** [comment]
Being in the foreground, it still needs 1,7% for doing nothing – what seems pretty much on an i7 to me. I tried to profile it by the new Builder profiler, but I've seen that I need the new flatpack builder for profiling other apps than the one compiled.

```
$ top | grep feedreader
15031 frank     20   0 3063356  88644  58048 S   1,7  0,5   0:11.80 feedreader  
15031 frank     20   0 3063356  88644  58048 S   1,3  0,5   0:11.84 feedreader  
15031 frank     20   0 3063356  88644  58048 S   5,3  0,5   0:12.00 feedreader  
15031 frank     20   0 3063356  88644  58048 S   4,7  0,5   0:12.14 feedreader  
15031 frank     20   0 3063356  88644  58048 S   1,7  0,5   0:12.19 feedreader  
15031 frank     20   0 3063356  88644  58048 S   1,7  0,5   0:12.24 feedreader  
15031 frank     20   0 3063356  88644  58048 S   1,7  0,5   0:12.29 feedreader  
15031 frank     20   0 3063356  88644  58048 S   1,7  0,5   0:12.34 feedreader  
15031 frank     20   0 3063356  88644  58048 S   1,3  0,5   0:12.38 feedreader
```
