### ISSUE TITLE
Feedly's saved-for-later syncs with feedreader's starred only one way.

### ISSUE THREAD

**Issue by V1ncam** [jangernert/FeedReader#271]
Articles that are starred with FeedReader get synced to Feedly as _saved for later_. However, articles that are marked as saved for later with Feedly, do no get synced to FeedReader as starred.

**Comment by jangernert** [comment]
Just tested it, and it works as intended.
Only a certain amount of articles (last 400 by default, or more if the number of unread articles on the server is bigger) are synced. But FeedReader can not check the status of every article on the server every time it syncs. This would increase the time it takes to sync and used bandwidth dramatically.
Some back-ends provide API to work around this problem by collecting all the changes since the last API request, but feedly does not provide such a method.
