### ISSUE TITLE
How to use "Local RSS"?

### ISSUE THREAD

**Issue by mimf** [jangernert/FeedReader#310]
Hello,

How does one use FeedReader without an online account? I want to use it locally. FeedReader asks me to login to 1 of 4 RSS services..

**Comment by jangernert** [comment]
You need to use master aka version 2.0-dev

**Comment by mimf** [comment]
Do you provide that version in a PPA? I see that you recently released 2.0beta1. Is that version in any ppa (or a .deb file for ubuntu 16.04)? I try to avoid installing from source as much as possible.

Thank you for the great software btw.

**Comment by jscurtu** [comment]
Currently not.. But you can try out the flatpake'd version from here:
https://github.com/jscurtu/feedreader-flatpak/releases

To install flatpak runtimes for Ubuntu look here:
http://flatpak.org/getting.html

**Comment by jangernert** [comment]
FeedReader 2.0 requires at least version 3.20 of Gtk+. And Ubuntu 16.04 only ships version 3.18. So I'm not sure the Flatpak will function correctly.

**Comment by jscurtu** [comment]
It should work as the flatpak'd application runs in a flatpaked runtime (3.22) that needs to be installed separately and is independently from its host version .

**Comment by ruppalsingh** [comment]
Any time-line on when 2.0 would be available on the PPA / as a debian package?

**Comment by jscurtu** [comment]
@ruppalsingh , the packing would need to be done by the community, till now none stepped up to do it. 
And as much as I am aware of, @jangernert stopped the distribution of FeedReader over the PPA channel due to some issues. 
For Ubuntu there will be a snap package of FeedReader at some point, I dont know what the current status is..
For now, we only have flatpak release, which runs fairly well and is installable with a single command:

`flatpak install http://feedreader.xarbit.net/feedreader-repo/feedreader.flatpakref`

**Comment by ruppalsingh** [comment]
Thank you. I am aware of the flatpak installation method -- but I was hoping a debian package would be available sooner or later. I guess I'll look for an alternative for the moment and check back here later. :/
