### ISSUE TITLE
Monthly payment

### ISSUE THREAD

**Issue by unculcated** [jangernert/FeedReader#328]
I filled in my credit card ready to pay 5 dollars a month, but wasn't prepared to pay yearly only. Increase it to 7 a month if you are worried about merchant fees

**Comment by bil-elmoussaoui** [comment]
We already use Bountrysource https://www.bountysource.com/teams/feedreader-gtk/issues You can put any amount of money on any bug you wish to see fixed :) Anyway, it's up to @jangernert to decide :)

@jangernert Btw, i think you should reconfigure Bountysource and use the Github issues tracker instead of the launchpad one as we don't use it anymore :P

**Comment by jangernert** [comment]
@bil-elmoussaoui Already removed the current launchpad bug-tracker and tried to add the github tracker. But adding a new tracker does not work with the web-interface. I mailed bountysource-support but haven't received an answer from them.

@unculcated sorry, but I'm not really following =/ If you want to support the project with money: great :)
I didn't even realize there was a way to simply pay a monthly amount directly. The usual way is to post money to a bug you would like to see fixed or a feature you want to have implemented. And as soon as the issue is closed the money is paid out to whoever wrote the code :)

**Comment by bil-elmoussaoui** [comment]
@jangernert Somehow Bountysource proposed to me to claim FeedReader project on BountySource as it's linked on my Github account, i fixed that and it seems that they created an other account for the Github issues https://www.bountysource.com/teams/jangernert-feedreader/issues
Sent you an admin inivitation (take a look at your emails). You should now be able to go to tools > click on FeedReader and then install in order to get the bounties to show up on Github issues :+1:

**Comment by jangernert** [comment]
@bil-elmoussaoui which email did you sent it to? Haven't gotten anything =/

**Comment by bil-elmoussaoui** [comment]
I've used your BountySource account id, i will check that right now

**Comment by bil-elmoussaoui** [comment]
It's done should be working fine right now :+1:

**Comment by bil-elmoussaoui** [comment]
@unculcated Just to let you know that BountySource owns Salt that can be used for giving a specific amount per month, the money given is used after that in Bountysource or claimed by the devs if needed https://salt.bountysource.com/checkout/amount?team=jangernert-feedreader

**Comment by jangernert** [comment]
yes, got the invite :)

**Comment by jangernert** [comment]
So I guess this is "solved" ?!
