### ISSUE TITLE
FeedReader does not sync with Tiny Tiny RSS

### ISSUE THREAD

**Issue by SuperNascher** [jangernert/FeedReader#409]
FeedReader does not mark Feeds as read or fetch the Feed updates in the current version with Tiny Tiny RSS. This works in the »FeedReader 2.0 beta1«, but with the current version it is broken.

**Comment by jangernert** [comment]
![1ke1gq](https://cloud.githubusercontent.com/assets/12012494/23344012/fff8d67c-fc74-11e6-8347-1d8dc4ec96a5.jpg)

**Comment by jangernert** [comment]
Logs or any information to work with here would help.

**Comment by SuperNascher** [comment]
I've created a screen cast to show the bug.

Here the 2.0.2 version:
https://www.youtube.com/watch?v=eWkAMC_oO34
(The log: https://n0paste.tk/TXlfMY1/ )

Here the 2.0-alpha, where it works:
https://www.youtube.com/watch?v=RKk8023x-lc
(The log: https://n0paste.tk/gJ2Qyxr/ )

**Comment by jangernert** [comment]
I need the log of the 'feedreader-daemon' process ;)

**Comment by jangernert** [comment]
Btw: it looks like the alpha is also not working "correctly".
The unread-counts are all calculated by what is actually in your database. So I have no idea why they are not showing up the moment the 2 new articles appear in the list.
Version 2.0.2 as well. If the back-end wasn't working the articles would be marked as read locally and the state would be overwritten during the next sync since the state was not changed on the server. But since somehow it doesn't work locally as well, it makes me think something else is up.
What version are you using? Traditional (package or compiled) or flatpak?
I would suggest trying to reset everything: log out of your account in FeedReader, close FeedReader, kill the running 'feedreader-daemon', delte all files in $HOME/.local/share/feedreader/data/ and try again ;)

**Comment by SuperNascher** [comment]
I compiled FeedReader.

After killing the daemon and deleting the data, it works without issues.
It seems, that I have broke something, but thanks for the help. :-)

**Comment by jangernert** [comment]
Glad I could help.
Rule of thumb: always kill the daemon after you installed/updated a new version ;)
