### ISSUE TITLE
Suspicious code in FeedServer.writeArticles()

### ISSUE THREAD

**Issue by brendanlong** [jangernert/FeedReader#446]
I noticed this as I was attempting to stop propagating the `LinkedList` class through all of the code (most of these should be `Gee.List`):

```
	private void writeArticles(Gee.LinkedList<article> articles)
	{
		if(articles.size > 0)
		{
			dbDaemon.get_default().update_articles(articles);
			var new_articles = new Gee.LinkedList<article>();

			var it = articles.bidir_list_iterator();
			for (var has_next = it.last(); has_next; has_next = it.previous())
				new_articles.add(it.get());

			dbDaemon.get_default().write_articles(new_articles);
			updateFeedList();
			updateArticleList();
		}
}
```

The section starting with `var it = articles.bidir_list_iterator()` seems very strange. We get an iterator, then loop through the entire list backwards and add the first article in the list to `new_articles` over and over again? Or am I reading this wrong?

If this code is correct, is it doing anything besides reversing the list?

**Comment by jangernert** [comment]
Yes, this is basically reversing the list. If I remember correctly this is because I wanted to write the last article in the list first iterating to the newest so the rowids in the db could be used to sort articles the way FeedReader received them from the backend (date is not always the best way to sort, at least for tt-rss).
But I guess one could just iterate the list backwards over here instead of copying all the data:
https://github.com/jangernert/FeedReader/blob/master/src/dbDaemon.vala#L569

**Comment by brendanlong** [comment]
I realized while writing #447 that this code was confusing me because of how Gee iterators work (`.next()` and `.previous()` mutate the iterator instead of returning a new one).
