### ISSUE TITLE
Download as an Appimage

### ISSUE THREAD

**Issue by nooryani84** [jangernert/FeedReader#488]
Could you include the app as an Appimage?  http://appimage.org/

**Comment by jangernert** [comment]
If a volunteer writes and keeps maintaining a build-script or something similar we are happy to merge it.
Otherwise no, I do not plan to get into any kind of packaging.
@jscurtu came along and merged his flatpak code. Appimage and Snap would each need someone like Jason, keeping track of all the moving parts of the package ;)
