### ISSUE TITLE
Add proxy support?

### ISSUE THREAD

**Issue by SammDu** [jangernert/FeedReader#521]
I live in a censored country but I hope to subscribe to some restricted feeds, but with FeedReader I don't see there's an option for proxy configuration (in Local mode).
I really hope that I can set my FeedReader to go through a proxy (socks v5) without touching anything globally, it'll be an awesome feature!
Hope you can take a look, THANKS!!!

**Comment by jangernert** [comment]
Not planned. I would suggest either to configure the proxy system wide or use a rss-reader that implements all sorts of advanced configurations in its UI.
Since FeedReader relies on libsoup, configuring a proxy works the same way it does for liferea:
https://lzone.de/liferea/blog/Liferea+Trick+%235%3A+Privacy+with+a+SOCKS+Proxy
