### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by ToeiRei** [jangernert/FeedReader#522]
I would love to have FeedReader running in the background minimized to the tray to have it out of the way until some news appear (notification popping up)

**Comment by bil-elmoussaoui** [comment]
The FeedReader Daemon (the binary that grabs your latest articles) is already running on the background. There's no need to keep the window running too.
FeedReader also follows some of elementary & GNOME HIG. And for both, tray icons are bad design decisions. 
So, this will be a won't fix

**Comment by qazip** [comment]
How is having a tray icon for an app that is minimized a bad design decisions? I much rather have it, so I know that something is running in the background, than not having and having annoying popups.

Some window managers (for example i3wm) do not have minimized windows, so I don't know if feedreader is running or not. Also, there should be an option for "close feedreader instead of minimizing it".

**Comment by brendanlong** [comment]
> Also, there should be an option for "close feedreader instead of minimizing it".

I would be in favor of making that the only option and not ever running in the background..
