### ISSUE TITLE
Any possible support for multiple accounts ?

### ISSUE THREAD

**Issue by kanishkablack** [jangernert/FeedReader#53]
Hai, is there any road map to support multiple accounts

FeedReader has perfect platform to be reading app like pocket or instapaper.

**Comment by jangernert** [comment]
No
FeedReader already does what these apps do:
- grab the full article
- style html
So instead of sending an article to instapaper just star it to remember to read it later in FeedReader.
I only integrated the sharing to online services when people want to read an article later on their mobile or a different pc.
So not in the near and intermediate future. Maybe when I run out of other ideas to implement. But right now there are much more important things to do.
