### ISSUE TITLE
Syncing locally 

### ISSUE THREAD

**Issue by DiggerD** [jangernert/FeedReader#601]
Hi, apologies, but I'm more of a linux user than developer..but I'll try and follow as best I can! 

I just installed Syncthing and I am hoping that I can use it to sync my RSS feeds locally. I have two machines at home. How would I go about having two machines (or more) share the same database files?

Thanks a lot for any of your time.

**Comment by jangernert** [comment]
The data is located in $HOME/.local/feedreader/data/. If you can mount a network share in place of that folder I guess it should work. This will not sync the settings and saved state of the application since they are stored in dconf, but all articles, images and icons should get synced that way.
But if you already have some kind of home server or a machine that is running 24/7 you could just as well self host tinytiny RSS, nextcloud, freshRSS or feedbin and sync way easier that way.

**Comment by brendanlong** [comment]
I would definitely advise setting up an RSS server instead of syncing the database. SyncThing can't merge SQLite databases, so you're inevitably going to run into merge conflicts every time you use a different computer.

**Comment by DiggerD** [comment]
thanks for your reply. 
if you are interested at some point in this, i found a thread at the syncthing forum:
https://forum.syncthing.net/t/synchting-as-database/8910

**Comment by brendanlong** [comment]
Yeah it's definitely possible, but it will be very fragile because SyncThing can't merge changes if two devices made changes to the database before syncing with each other.
