### ISSUE TITLE
Medium.com RSS feeds fail silently with local parser

### ISSUE THREAD

**Issue by darthoctopus** [jangernert/FeedReader#611]
See `https://medium.com/feed/the-physics-arxiv-blog` for an example. The RSS XML is well-formed, but feedreader fails to detect any entries, with no error messages being returned.

**Comment by brendanlong** [comment]
I looked into this more and what's happening is that the articles are too old, so we're deleting them by default. If you go to `Settings` -> `Internals` -> `Database` -> `Delete articles after` and set it to `Never` and then sync again they should show up.

This behavior is kind of annoying but it's working as expected.

@jangernert I wonder if there's anything we could do to make this less confusing. Ideally we would leave unread articles alone by default, but then deleting old articles would be kind of pointless since they'd still be in the database to track their read status. It might be less confusing if the default value of `Delete articles after` was `Never`? Or maybe we should show some sort of feedback to make it clear that we found articles but are intentionally ignoring them. If you have a preferred way to handle this I can work on it, I'm just not sure what the right thing to do here is.

**Comment by brendanlong** [comment]
@bilelmoussaoui At one point you added this to a milestone. Do you have any ideas for changes we should make to make this less confusing? I was considering closing the issue since the parser and settings are working as-intended, although I'd be happy if there was some way to make it less confusing.

**Comment by brendanlong** [comment]
I guess one option would be to show it in the notification (`x new articles (y old articles skipped)`).

**Comment by bilelmoussaoui** [comment]
I don't remember doing that at all, but I don't think there were any changes since I added this issue to a milestone. I think we can close this safely as we have got no feedback in almost two years :/
