### ISSUE TITLE
Mark items as read by scrolling past them

### ISSUE THREAD

**Issue by arjan-s** [jangernert/FeedReader#63]
I'm using the ownCloud News Reader Android app and it has this nice feature. When I scroll through the articles list, it automatically marks the articles read that scroll past the top of my screen. This makes it really easy to go through a part the list, without needing to mark or open every single article of which I've seen the headline.

**Comment by HoratiuMl** [comment]
Good idea but if you decide to implement it, please add is as an option in the settings menu. While I think it's a useful feature, I think I like the current behaviour more, and other people might as well. I think giving this as an option is the best way to do it, to please everyone.

**Comment by jangernert** [comment]
Please test this in depth. This feature could potentially break in various ways.

**Comment by arjan-s** [comment]
Love the feature already! :)
I do have a minor issue with it though: the "All articles" unread counter doesn't work correctly. It is usually way too low or even empty/zero, while one of the feeds or categories can have tens of unread articles.

**Comment by jangernert** [comment]
@arjan-s that is very weird, because the unread counts are read directly from the dataBase by counting the actual unread articles. The only thing I can think of that could go wrong is adding up the unread articles of the feeds to the unread-count of the categories. OwnCloud doesn't allow feeds in multiple categories at once and similar things, right?
Despite all this I improved the feature a bit with the latest commits so it doesn't trigger for every pixel scrolled and doesn't trigger during loading-actions. Maybe this already improves your situation.
If you still can properly reproduce the issues please open up another report for this.
