### ISSUE TITLE
no sync with tt-rss

### ISSUE THREAD

**Issue by gackelchen** [jangernert/FeedReader#643]
After installation and configuration synchronization works but only at the first time. After this I can't get new feeds. Only if I configure the account for a second time it works again, but again only once.

**Comment by brendanlong** [comment]
Can you check if you're still seeing this with the latest release (v2.8.0)? I made some substantial general improvements to our TT-RSS support (on both the FeedReader and api_feedreader side).

I'm closing tickets I think should be fixed by v2.8.0 but please re-open this if you're still seeing the same problem!
