### ISSUE TITLE
Make GrabberConfig a subtree

### ISSUE THREAD

**Issue by bil-elmoussaoui** [jangernert/FeedReader#70]
I think it's better to make the [GrabberConfig](https://github.com/jangernert/FeedReader/tree/master/data/GrabberConfig) folder a subtree of [fivefilters/ftr-site-config](https://github.com/fivefilters/ftr-site-config)
This will auto update the grabber config folder whenever the user clones the repo

**Comment by jangernert** [comment]
I just looked into it for a bit. Seems to make things more complicated since I still carry a patch for phoronix.com. So basically every time the subtree (or submodule) would be updated the patch would have to be applied.
If anyone wants to automate that they are very much welcome. But right now I think it's enough to update the config once before every release.
