### ISSUE TITLE
Feature: Support non-GNOME proxies

### ISSUE THREAD

**Issue by RafaelLinux** [jangernert/FeedReader#778]
I'm just trying FeedReader, but after selectiing "Feedly" on main menu it just shows:
> "Error resolving “cloud.feedly.com”: Name or service not known"
so I can use Feedreader behind a proxy.

Please, could you implement this feature (use proxy setting, proxy PAC file, etc...)

Thank you

**Comment by brendanlong** [comment]
It sounds like libsoup should be using system proxies by default:

https://developer.gnome.org/libsoup/stable/SoupProxyResolverDefault.html

> In libsoup 2.44 and later, you can set the session's “proxy-resolver” property to the resolver returned by g_proxy_resolver_get_default() to get the same effect. Note that for "plain" SoupSessions (ie, not SoupSessionAsync or SoupSessionSync), this is done for you automatically.

Is your proxy setup in GNOME's Network settings?

**Comment by RafaelLinux** [comment]
No. I'm using KDE Plasma, so I have the proxy setting using KDE network proxy settings. Using several GTK applications that needs proxy, but must of them have their own proxy setting so they all are working fine. That's why I ask for a proxy settings menu inside FeedReader.

**Comment by brendanlong** [comment]
Unfortunately I don't think this is the sort of thing we're likely to support anytime soon. As a GNOME application, we expect proxies to be configured on a system level, not per-application and I don't think we're willing to take on the costs this brings us right now (more options = more work and more bugs). I suspect the best way to solve this problem would be make libsoup able to lookup KDE's proxy settings, not to add that setting to FeedReader.

That said, if we had an active contributor who wanted to add and support this feature I'd be willing to go along with it, but I don't think any of our current contributors are likely to do it. This is way more work than it sounds like though, since if anyone wanted to do this, they'd need to start by centralizing our disparate libsoup configurations (which is a good idea, but non-trivial).

**Comment by jtojnar** [comment]
`glib-networking` contains a proxy resolver using [libproxy](http://libproxy.github.io/libproxy/), which should support KDE. Are you sure you have the module installed? For example, on Arch, it will be in `/usr/lib/gio/modules/libgiolibproxy.so`, provided by [`glib-networking`](https://www.archlinux.org/packages/extra/x86_64/glib-networking/) package.

**Comment by bilelmoussaoui** [comment]
Any news on this?

**Comment by brendanlong** [comment]
Is there anything special we need to do to support libproxy?

Unfortunately I don't really have time for feature requests but this might be something we'd accept if it could be done in a straightforward way and someone else was willing to write the code.

**Comment by jtojnar** [comment]
I believe it is supported out of the box, if you use the standard `SoupSession`:

https://developer.gnome.org/libsoup/stable/SoupSession.html#SoupSession--proxy-resolver
https://developer.gnome.org/gio/stable/GProxyResolver.html#GProxyResolver.description

User just needs to make sure it has the [necessary module](https://github.com/jangernert/FeedReader/issues/778#issuecomment-447691095) installed.

**Comment by brendanlong** [comment]
It sounds like this should already be done, and it's up to non-GNOME packagers to get the necessary modules installed.
