### ISSUE TITLE
repository for Ubuntu 16.04 / Elementary Loki 0.4

### ISSUE THREAD

**Issue by okias** [jangernert/FeedReader#79]
I just switched and can't find any workin repository.

Would you consider also building it for 16.04?

Thank you
David

**Comment by jangernert** [comment]
once elementary releases a open beta or some development iso's I will update the ppa

**Comment by DroWnThePoor** [comment]
Where can I find the PPA? I ended up installing this on Loki from Flatpak and I hate the Adwaita theme. I notice that all of the screenshots here look like it's using granite, and I ended up here from https://madeforelementary.tumblr.com/
Would love to install this from a ppa on Loki.

**Comment by jangernert** [comment]
@DroWnThePoor The ppa isn't maintained any more and only contains a very outdated version. The problem is that FeedReader depends on Gtk+ >= 3.20 and elementary only ships 3.18. This problem is solved by flatpak with their runtimes.

**Comment by DroWnThePoor** [comment]
Thank you for the reply, I'd still like to maybe try to the outdated version in the PPA IF it would be possible to install in Loki. Alternatively, how hard would it be to "theme" the Flatpak? I know there are a limited number of themes available for Flatpaks. Is it possible to build libgranite with Gtk+ 3.20?


On Tue, Jul 25, 2017 at 3:58 PM, Jan Lukas Gernert <notifications@github.com> wrote:

@DroWnThePoor<https://github.com/drownthepoor> The ppa isn't maintained any more and only contains a very outdated version. The problem is that FeedReader depends on Gtk+ >= 3.20 and elementary only ships 3.18. This problem is solved by flatpak with their runtimes.
