### ISSUE TITLE
FeedReader doesn't respect font scaling

### ISSUE THREAD

**Issue by aboettger-tuhh** [jangernert/FeedReader#812]
![image](https://user-images.githubusercontent.com/17931448/49383163-688ac200-f718-11e8-81f3-3593263cca61.png)

**Comment by jangernert** [comment]
For HiDpi use the [gdk scale factor](https://wiki.gnome.org/HowDoI/HiDpi). If you have a [poor resolution/size ratio](https://medium.com/elementaryos/top-3-misconceptions-about-hidpi-f5ef493d7bf8) and you feel you 'need' fractional scaling there is an [experimental feature](https://wiki.archlinux.org/index.php/HiDPI#Fractional_Scaling) in mutter.

**Comment by brendanlong** [comment]
I'm going to close this since it seems like we do support this, just not necessarily with the interface you'd like. With the very limited amount of time any of us have to spend on this project, I don't think it's likely that we'll implement additional scaling logic besides what's provided for us by GDK.
