### ISSUE TITLE
Import xml files from websites

### ISSUE THREAD

**Issue by razaalghul** [jangernert/FeedReader#832]
Hello team, I just discovered feedreader today and I'm planning to use it to follow many of my websites and newsletters.
I need help with 2 things please:
1- How do I backup my data so if the app crashes I can recover everything
2- How do I import xml files please? I'm on Linux Mint 19.1 and I realized that many websites download an xml file that I need to open with feedreader, but it seems like feedreader doesn't open them.

Can you help a newbie here please?

**Comment by brendanlong** [comment]
For backup purposes, I would recommend using a remote service like Feedbin, NextCloud, etc. instead of the local backend. Most remote services will also let you import and export all of your feeds as an [OPML file](https://en.wikipedia.org/wiki/OPML). Last time I checked, FeedReader can import OPML files in some cases but we don't currently have a way to generate them (see #334).

To add new RSS feeds, FeedReader can't just open the feed XML, it actually needs to know the URL of it (so it knows where to look for updates). You could be able to get the URL either from the title bar of your browser, or by right clicking the RSS link and choosing "copy link location". Once you have that, you can click the "+" button in the bottom left corner of FeedReader, paste the link in there, and it should synchronize and download the feed (and will re-check that feed every time it syncs in the future).

I hope this helps. I'm closing this because I think #334 covers the only change that you're requesting.
