### ISSUE TITLE
[Feature Request] New Article Notification

### ISSUE THREAD

**Issue by zero77** [jangernert/FeedReader#846]
Can you please add notification support for new article even when the window isn't open.
Thanks

**Comment by brendanlong** [comment]
This exists, although it's confusing. If you click the close [x] button, the window will close but FeedReader will continue running the background (with notifications). I'm considering removing this though, since it's confusing for the app to run in the background (if people want an app to keep running, they can leave it open..).

**Comment by zero77** [comment]
@brendanlong  
> I'm considering removing this though, since it's confusing for the app to run in the background (if people want an app to keep running, they can leave it open..).

Can you make it optional instead of disabling it completely.

Also, leaving it open may be hard for people using a window manager like i3 although, you could just leave it open but in the system tray.
Thanks

**Comment by zero77** [comment]
I think the tray icon may be the best approach.
Should i open an issue.

**Comment by jangernert** [comment]
Tray icon has been requested pretty often already. But most of us are against that idea #779
