### ISSUE TITLE
Notification shows total unread rather than unread since last sync 

### ISSUE THREAD

**Issue by pank** [jangernert/FeedReader#86]
Hi,

When I sync the reader I'm showed how many articles are unread in total.
I think it would be more informative to show how many new unread articles were added (i.e. the difference between total unread before and after the sync).

Thanks,
Rasmus

**Comment by jangernert** [comment]
And when you miss just one of these notifications, FeedReader will keep quiet even though there could be lots of new unread articles. Just because there were no new articles the next sync 10 minutes later =/
I originally had it that way but it annoyed the hell out of me. So not a big fan over here.
But I added it as a tweaks option (dconf only).
