### ISSUE TITLE
Local fetcher is unable to deal with feeds that are behind cloudflare

### ISSUE THREAD

**Issue by nagisa** [jangernert/FeedReader#871]
Those feeds may trigger the cloudflare’s "checking your browser” nonsense, which FeedReader will in turn be unable to parse as a feed.

There should be a way to somehow pretend to be an user and wait out those few seconds for feeds that have the nonsense in front of them.

**Comment by brendanlong** [comment]
There's not really any good way for us to do this. We'd have to load feeds in a browser (which would be really slow), and then run arbitrary JavaScript in the background (potentially a security issue), and then wait an arbitrary amount of time for the page to refresh itself (in a way that we probably can't detect easily) and then check if the text content of the page is a valid XML document.

I am somewhat curious if anyone implements this logic, since it would be interesting to see how much effort it takes. I'm a little worried that even if we did, it would be obvious that we *are* in fact a robot and then CloudFront would just block us anyway..

Unfortunately, these feeds are completely broken and the only people who are in a good position to fix them are the websites' owners.

**Comment by nagisa** [comment]
Fair.
