### ISSUE TITLE
FeedReader causes excessive disk writes

### ISSUE THREAD

**Issue by erlenmayr** [jangernert/FeedReader#970]
I noticed that gnome-shell is writing gigabytes of data to disk. Checking out SystemD logs for gnome-shell, it turns out that out of 1001 entries in the logs for gnome-shell, 974 are caused by FeedReader.

gnome-shell and systemd are both reported to have written gigabytes of data to disk, 7.6 GB and 14 GB, respectively. Next in the top disk writers are gvfs and Firefox, each around 400 MB and both expected to write data. gnome-shell is not expected to write data at all.

Something is not right here. For now it looks like FeedReader is logging way too much stuff, especially uninteresting stuff. I will try to investigate it more.

**Comment by erlenmayr** [comment]
The log is full with weird stuff like this.
[feedreader.log](https://github.com/jangernert/FeedReader/files/3989603/feedreader.log)

**Comment by pwithnall** [comment]
I think #982 should fix this, but haven’t actually tested, because assembling all the build dependencies is too much of a pain at the moment. I’m fairly confident this is the right fix, though, since the logs are full of debug output from FeedReader *and* other libraries (like GDK), which would only appear if the log writer function is letting them through.

**Comment by erlenmayr** [comment]
I just built it from scratch after checking out from Github. It now does not cause much disk writes of Gnome Shell and JournalD any more, however it still has a lot of disk writes.
FeedReader was running for one hour, update interval set to 15 minutes, writing 500 MB of space. Only a few feeds are in there, there is no explanation for that large amount.
